name = "everest-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]   # ⭐ هر دقیقه

[[kv_namespaces]]
binding = "KV"
id = "b7ab0b5f26ac48688335705c7a507a4c"  # ID کیو وی خودت